### ISSUE TITLE
Routing in app.js

### ISSUE THREAD

**Issue by RohanSSS** [FAC-Sixteen/Smoothie-bar#22]
You have your routing for all your controllers in app.js
This is fine for the small amount of pages in our apps, but with something larger it may begin to make app.js seem a little big.

You can instead do this with an index.js file inside controllers, which you reference in app.js with:
```
const controllers = require('./controllers/index');

app.use(controllers);
```
Once you've got that you can use express's inbuilt router function to do the routing

```
const router = express.Router();

const home = require('./home');

router.get('/', home.get);

module.exports = router;
```

**Comment by dubhcait** [comment]
couldn't agree more. it was a conscious decision as our project had so few controllors
