### ISSUE TITLE
the svg matrix

### ISSUE THREAD

**Issue by Fweddi** [FAC-Sixteen/Smoothie-bar#24]
Is there a way of exporting the svg from an external file, so that home.hbs could be more readable?

**Comment by RohanSSS** [comment]
Or possibly making it a partial due to the fact that it's used multiple times, so you don't have to repeat the code for it

**Comment by RohanSSS** [comment]
You could feed in an object of all the smoothie flavors into the home render, and then just use that object with `{{#each }}` to generate all of the svg's

**Comment by dubhcait** [comment]
coolio will try
